# Site settings
title: Semantic Werks
locale: "en-US"
tagline: Thoughts on research, software and methodology.
email: neil@neilernst.net
description: > # this means to ignore newlines until "baseurl"
  Thoughts on research, software and other topics.
#url: "http://neilernst.github.io"
url: "http://www.neilernst.net"
#url: "http://localhost:4000"
minimal_mistakes_skin    : "default" # "air", "contrast", "dark", "dirt", "mint", "sunrise"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: true
      # share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

words_per_minute         : 200
comments:
  provider               : disqus # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
  disqus:
    shortname            : semantic-werks # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
# staticman:
#   allowedFields          : ['name', 'email', 'url', 'message']
#   branch                 : # "master", "gh-pages"
#   commitMessage          : "New comment."
#   filename               : comment-{@timestamp}
#   format                 : "yml"
#   moderation             : true
#   path                   : "_data/comments/{options.slug}"
#   requiredFields         : ['name', 'email', 'message']
#   transforms:
#     email                : "md5"
#   generatedFields:
#     date:
#       type               : "date"
#       options:
#         format           : "iso8601" # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
# atom_feed:
#   path                   : # blank (default) uses feed.xml


# Social Sharing
twitter:
  username               : neilernst
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : #Person # Person or Organization (defaults to Person)
  name                   : #Neil Ernst # If the user or organization name differs from the site's name
  links                  :    # An array of links to social media profiles

# Analytics
analytics:
  provider               : false #(default), "google", "google-universal", "custom"
  google:
    tracking_id          :  UA-3378072-1 # neilersnt.net UA-3378072-1 neilernst.github UA-86878691-1

# Site Author
author:
  name             : "Neil Ernst"
  avatar           : "/images/neil-ernst-small.jpg"
  bio              : ""
  location         : V8P 5C2
  email            : "neil@neilernst.net"
  uri              :
  bitbucket        :
  codepen          :
  google_scholar   : neilernst
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : neilernst
  twitter          : neilernst
  gitlab           :
  google_plus      :
  keybase          : neilernst
  instagram        :
  lastfm           :
  linkedin         : neilernst
  pinterest        :
  soundcloud       :
  stackoverflow    :  888483/neil #(the last part of your profile url, e.g. http://stackoverflow.com/users/123456/username)


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

prose:
  rooturl: '_posts'
  siteurl: 'http://neilernst.net'
  relativeLinks: 'http://neilernst.net/links.jsonp'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add Categories"
          placeholder: "Add Categories"
          alterable: true
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "image"
        field:
          element: "text"
          label: "Add Image to Post"
          placeholder: "Image path (relative to /assets/post-images/)"
          alterable: true
      - name: "excerpt_separator"
        field:
          element: "hidden"
          value: "<!--more-->"

