# Site settings
title: Semantic Werks
tagline: Thoughts on research, software and methodology.
email: neil@neilernst.net
description: > # this means to ignore newlines until "baseurl"
  Thoughts on research, software and other topics.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://neilernst.net" # the base hostname & protocol for your site
twitter_username: neilernst
github_username:  neilernst
paginate: 5

# Build settings
markdown: kramdown
highlighter: rouge
sass:
    style: :compressed

# Gems
gems: [jekyll-paginate]
